spring:
    datasource:
        username: alexandrexaw
        password: 123trocar
        url: jdbc:mysql://pridedevdatabase.c3lbe0bvk2jp.us-east-1.rds.amazonaws.com/alexandrexaw
    jpa:
        hibernate:
            ddl-auto: update

